# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

steps:

- task: UseDotNet@2
  displayName: 'Use .NET SDK'
  inputs:
    version: 9.0.x

- script: dotnet run --project $(Build.SourcesDirectory)/nukebuild/_build.csproj -- RunTests --configuration Release
  displayName: 'Run Unit Tests'

- script: dotnet run --project $(Build.SourcesDirectory)/nukebuild/_build.csproj -- Package --configuration Release
  displayName: 'Generate Nuget Package'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/src/Avalonia.Controls.TreeDataGrid/bin/Release/'
    ArtifactName: 'drop'
    publishLocation: 'Container'
